### ISSUE TITLE
ibv_reg_mr fail: could not get umem for mem region

### ISSUE THREAD

**Issue by srinivasgowda** [zzaoen/RdmaAcceleratingRedis#1]
Hi,
I found this to be a very interesting project. 
I have two questions for you. 
1.  You are suggesting to run redis_server on both master and slave in section "4.3 RDMA Data Synchronization Scheme", however at this stage the redis server is already running as instructed in section "4.1 Master-Slave Cluster" . Can you please clarify the steps to be followed before starting the rdma_client ? 
2. I tried following the steps that you suggested (except rerunning the redis server again - Section 4.3) , however I`m seeing the following failure 
 ./rdma-client 100.71.96.214 12345
error: conn->rdma_local_mr = ibv_reg_mr(s_ctx->pd, conn->rdma_local_region, (data_size + max_mapping_table_size), IBV_ACCESS_LOCAL_WRITE | IBV_ACCESS_REMOTE_READ) failed (returned zero/null).

dmesg
0000:0b:00.1: could not get umem for mem region

Any suggestion as to what could be wrong here ?

**Comment by zzaoen** [comment]
Hi @srinivasgowda. I am so sorry, I didn't maintain this repo for a long time. Since I've been leaving the Lab for 2 years, I can't help you with this question.
I hope you've already solved this issue.

**Comment by srinivasgowda** [comment]
Thanks for responding @zzaoen . I`m not actively looking at this now.
